// Generated for: Tandem.NodeApiSpike.Bridge 0.1.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.9.0.0
/* eslint-disable */

import './System.Runtime';


/** Adapts JavaScript-authored participants to the Tandem runtime. */
export namespace NodePipelineBridge {
	/** Reads accepted semantic journal values from a packaged SQLite ledger. */
	export function inspectAcceptedAsync(
		ledgerPath: string,
		runId: string,
	): Promise<string>;

	/** Registers and runs a complete JavaScript-authored Tandem graph. */
	export function runRegisteredGraphAsync(
		definitionJson: string,
		invokeSyncCallback: Func$4<string, string, string, string>,
		invokeAsyncCallback: Func$5<string, string, string, AbortSignal, Promise<string>>,
		cancellationToken?: AbortSignal,
	): Promise<string>;
}
