// Generated for: Tandem.Bridge 0.3.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.9.0.0
/* eslint-disable */

import './System.Runtime';


/** Adapts JavaScript-authored participants to the Tandem runtime. */
export namespace NodePipelineBridge {
	/** Executes a declared agent within an active collection item. */
	export function runCollectionAgentAsync(
		scopeId: string,
		agentId: string,
		state: string,
	): Promise<string>;

	/** Reads accepted semantic journal values from a packaged SQLite ledger. */
	export function inspectAcceptedAsync(
		ledgerPath: string,
		runId: string,
	): Promise<string>;

	/**
	 * Registers and runs a complete JavaScript-authored Tandem graph and reports how it
	 * ended as a {@link Tandem.Bridge.RunEnvelope}. Once a run is attempted every failure is
	 * reported, because a fault raised inside the run cannot be told apart from a bridge
	 * defect; a fault carries the full exception text. Only a caller without a JavaScript
	 * synchronization context gets an exception.
	 */
	export function runRegisteredGraphAsync(
		definitionJson: string,
		invokeSyncCallback: Func$4<string, string, string, string>,
		invokeAsyncCallback: Func$5<string, string, string, AbortSignal, Promise<string>>,
		cancellationToken?: AbortSignal,
	): Promise<string>;
}
